version: '3.0'

services:
  rasa:
    image: rasa/rasa:2.0.0rc4-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./:/app/"
    command:
    - run

  action_server:
    build: .
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: rasa
      MONGO_INITDB_ROOT_USERNAME: <username>
      MONGO_INITDB_ROOT_PASSWORD: <password>
    networks: ['rasa-network']
    ports:
      - "27017-27019:27017-27019"
  mongo-express:  # this service is a MongoDB UI, and is optional
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    networks: ['rasa-network']
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: <username>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <password>

networks: {rasa-network: {}}
