version: '3.0'

services:
  rasa:
    image: rasa/rasa:2.0.0rc3-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./:/app/"
    command:
    - run

  action_server:
    build: .
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

networks: {rasa-network: {}}
